services:
  - type: web
    name: together-backend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_SYNC
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "30"
      - key: CORS_ORIGINS
        value: '["https://together-frontend-jgo1-eta.vercel.app","http://localhost:3000","http://localhost:8081"]'
      - key: APP_ENV
        value: production
      - key: APP_NAME
        value: Together API
      - key: APP_VERSION
        value: v1
      - key: DEBUG
        value: "false"
      - key: GOOGLE_WEB_CLIENT_ID
        sync: false
      - key: GOOGLE_WEB_CLIENT_SECRET
        sync: false
      - key: GOOGLE_ANDROID_CLIENT_ID
        sync: false
      - key: GOOGLE_IOS_CLIENT_ID
        sync: false
